[build]
  # 빌드 명령어를 아예 없애서 넷리파이가 헛수고하지 않게 합니다.
  command = "echo 'No build needed'"
  # 우리가 서비스할 진짜 폴더 주소
  publish = "jerrykeyring_legacy"

# 넷리파이의 Next.js 자동 감지 기능을 강제로 끕니다.
[build.environment]
  NETLIFY_NEXTJS_SKIP_PREPARE = "true"

[[redirects]]
  from = "/nfc/*"
  to = "/nfc/:splat.html"
  status = 200
